apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:

  # Number of pods to create for MiniCluster
  size: 2

  # Cleanup the storage volume (PVC and PV) after run
  cleanup: true

  # show all operator output and test run output
  logging:
    quiet: false

  pod:
    # This should be the service account you created
    serviceAccountName: flux-operator-gke

    # This annotation is required for the driver
    annotations:
      gke-gcsfuse/volumes: "true"

  # Make this kind of persistent volume and claim available to pods
  # This is a type of storage that will use Google Storage
  volumes:
    data:      
      class: dummy-storage-class
      driver: gcsfuse.csi.storage.gke.io 
      path: /tmp/data
      capacity: 25Gi
      secret: gcs-fuse-csi-node-sa-token-2r6r9
      volumeHandle: flux-operator-storage

  # This is a list because a pod can support multiple containers
  containers:

      # This image has snakemake installed, and although it has data, we will 
      # provide it as a volume to the container to demonstrate that (and share it)
    - image: ghcr.io/rse-ops/atacseq:app-latest

      # We are saying to mount the "data" volume defined above to "/workflow"
      # in the container
      volumes:
        data:
          # This is where we will bind storage
          path: /workflow
          # readonly defaults to false
                
      # This should be the directory with the Snakefile
      workingDir: /workflow/snakemake-workflow
      command: snakemake --cores 1 --flux

      # Commands just for workers / broker
      commands:

        # This is currently required for the storage driver to work
        runFluxAsRoot: true