# permissions for end users to view fluxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-viewer-role
rules:
- apiGroups:
  - flux-framework.org
  resources:
  - fluxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flux-framework.org
  resources:
  - fluxes/status
  verbs:
  - get
