# permissions for end users to edit fluxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-editor-role
rules:
- apiGroups:
  - flux-framework.org
  resources:
  - fluxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux-framework.org
  resources:
  - fluxes/status
  verbs:
  - get
