apiVersion: flux-framework.org/v1alpha1
kind: MiniCluster
metadata:
  name: flux-sample
  namespace: flux-operator
spec:
  # Number of pods to create for MiniCluster
  size: 2

  # suppress all output except for test run
  logging:
    quiet: true
    strict: false

  # kubectl apply -f ./examples/simulations/qmcpack/minicluster.yaml
  # Then watch logs of the broker pod: kubectl logs -n flux-operator <pod> -f
  containers:
    - image: ghcr.io/rse-ops/qmcpack:qmcpack-3.13.0

      # You can set the working directory if your container WORKDIR is not correct.
      workingDir: /coral2/NiO/dmc-a32-e384-batched_driver-DU32/
      command: qmcpack NiO-fcc-S8-dmc-strongscale.xml